import type { InvestigationResult } from '../types.js'

export class PatchEngine {
  static toUnifiedDiff(result: InvestigationResult): string {
    if (!result.fix) return '# No fix available from investigation'

    const lines = result.fix.split('\n')
    const isAlreadyDiff = lines.some(l => l.startsWith('---') || l.startsWith('+++') || l.startsWith('@@'))
    if (isAlreadyDiff) return result.fix

    // Wrap raw fix in a unified diff format
    const file = result.filesToModify?.[0] || 'src/unknown.ts'
    const header = [
      `--- a/${file}`,
      `+++ b/${file}`,
      '@@ -1,0 +1,0 @@'
    ]

    const diffBody = lines.map(line => {
      if (line.startsWith('+') || line.startsWith('-')) return line
      return ` ${line}`
    })

    return [...header, ...diffBody].join('\n')
  }

  static toPatchFile(result: InvestigationResult): string {
    const diff = PatchEngine.toUnifiedDiff(result)
    const header = [
      `Subject: [PATCH] Dr. Debug Auto-Fix: ${result.diagnosis.slice(0, 60)}`,
      `Date: ${new Date().toISOString()}`,
      `Confidence: ${(result.confidence * 100).toFixed(0)}%`,
      '',
      result.diagnosis,
      '',
      `Root Cause: ${result.rootCause}`,
      '---',
      ''
    ]
    return [...header, diff, '', '-- ', 'Generated by Dr. Debug Autonomous Debugging Agent'].join('\n')
  }

  static toGitHubPRBody(result: InvestigationResult, interactionReplay?: string): string {
    const sections = [
      '## 🩺 Dr. Debug Autonomous Diagnosis',
      '',
      `**Confidence:** ${(result.confidence * 100).toFixed(0)}%`,
      `**Status:** ${result.status}`,
      `**Duration:** ${result.durationMs}ms`,
      '',
      '### 🔍 Diagnosis',
      result.diagnosis,
      '',
      '### 🎯 Root Cause',
      result.rootCause,
      ''
    ]

    if (result.filesToModify && result.filesToModify.length > 0) {
      sections.push('### 📁 Files Modified')
      result.filesToModify.forEach(f => sections.push(`- \`${f}\``))
      sections.push('')
    }

    if (interactionReplay) {
      sections.push('### 🖱️ User Interaction Replay (Reproduction Steps)')
      sections.push('```')
      sections.push(interactionReplay)
      sections.push('```')
      sections.push('')
    }

    if (result.fix) {
      sections.push('### 🛠️ Applied Fix')
      sections.push('```diff')
      sections.push(PatchEngine.toUnifiedDiff(result))
      sections.push('```')
    }

    sections.push('')
    sections.push('---')
    sections.push('*Auto-generated by Dr. Debug — Autonomous In-Browser AI Debugging Agent*')

    return sections.join('\n')
  }

  static validatePatch(patch: string): { valid: boolean; errors: string[] } {
    const errors: string[] = []
    const lines = patch.split('\n')

    const hasMinus = lines.some(l => l.startsWith('--- '))
    const hasPlus = lines.some(l => l.startsWith('+++ '))
    const hasHunk = lines.some(l => l.startsWith('@@'))

    if (!hasMinus) errors.push('Missing --- header line')
    if (!hasPlus) errors.push('Missing +++ header line')
    if (!hasHunk) errors.push('Missing @@ hunk header')

    return { valid: errors.length === 0, errors }
  }
}
